# Site settings
url: https://techmasters.chat
title: "#TechMasters"
description: Connect with fellow Technologists &amp; Founders, Get help with coding problems, Discuss your startup goals and Learn new skills

# Build settings
markdown: kramdown

# Google Calendar API settings
googleCalendar:
  apiKey: AIzaSyD3Y_GF0P3MSCWZKhkMQ0FrUfKUf07m4U4
  calendarId: zamtools.com_sksehlk62uahqednpmvbp7isno@group.calendar.google.com

exclude: [scripts]

gems:
  - jekyll-redirect-from
