# Site settings
url: https://techmasters.chat
title: Technology Masters
description: >
  An online community tying together a diverse and passionate group of technologists, entrepreneurs, and developers from all around the world.

# Build settings
markdown: kramdown
